### ISSUE TITLE
clusterperm.lmer throws errors when predictors are set to sum-to-zero contrasts

### ISSUE THREAD

**Issue by hy-lu** [cvoeten/permutes#3]
Hi,

I'm so happy and grateful that I've found this package! This really eases the pain of doing cluster-based permutation tests in R by hand.
I used clusterperm.lmer function to do an LME model but it threw errors and warnings like this:

```r
Error in `*tmp*`[[i]] : subscript out of bounds #
In addition: Warning message:
In x[, ii] : subscript out of bounds
```

I looked into the source code and thought it was probably related to this: https://github.com/cvoeten/permutes/blob/67adb4fa968898f0d2d5f2cf21be2e25830213e6/R/buildmer.R#L237
When factors were in sum-to-zero contrast, the colnames of X and X.restricted were different in terms of interaction terms. Specifically, in X, interaction terms were named in the fashion of global contrast settings, whereas in X.restricted they were named as the treatment contras. This would result in mismatch between normalized.colnames(X) and normalized.colnames(X.restricted). But I'm not sure it's a bug or how it's supposed to be.

Here is a reproducible example using MMN data:

```r
# Factorize Deviant and Session 
MMN2 <- MMN;
MMN2$Deviant <- factor(MMN2$Deviant, levels = c(1, 0), labels = c("Y","N"));
MMN2$Session <- factor(MMN2$Session, levels = c(0, 1), labels = c("First", "Second"))

# Set to treatment contrast globally
options(contrasts=c('contr.treatment', 'contr.poly'))
# would work perfectly
perms <- clusterperm.lmer(Fz ~ Deviant*Session + (1|Subject),data=MMN2[MMN2$Time > 200 & MMN2$Time < 205,],series.var=~Time,nperm=2,type='anova')
```
```r
> perms
   Time Measure          Factor df          LRT           F cluster cluster_mass         p
1     1      Fz               1  1   0.05259208  0.02630683       0           NA 0.6666667
2     1      Fz         Deviant  1  99.81655278 37.78548192       1     301.0653 0.0000000
3     1      Fz         Session  1  37.70341008  9.48034100       1     108.9461 0.0000000
4     1      Fz Deviant:Session  1   2.48234062  0.55558189       0           NA 0.0000000
5     2      Fz               1  1   0.05075017  0.06332415       0           NA 0.6666667
6     2      Fz         Deviant  1 100.51793579 38.30194463       1     301.0653 0.0000000
7     2      Fz         Session  1  36.62701197  9.18267128       1     108.9461 0.0000000
8     2      Fz Deviant:Session  1   2.28182540  0.51143504       0           NA 0.0000000
9     3      Fz               1  1   0.04938611  0.12764599       0           NA 0.6666667
10    3      Fz         Deviant  1 100.73077249 38.53914582       1     301.0653 0.0000000
11    3      Fz         Session  1  34.61563100  8.61358034       1     108.9461 0.0000000
12    3      Fz Deviant:Session  1   1.88323658  0.42246020       0           NA 0.3333333
   p.cluster_mass
1              NA
2       0.3333333
3       0.3333333
4              NA
5              NA
6       0.3333333
7       0.3333333
8              NA
9              NA
10      0.3333333
11      0.3333333
12             NA
```
```r
# would not work when using sum-to-zero contrast
options(contrasts=c('contr.sum', 'contr.poly'))
perms2 <- clusterperm.lmer(Fz ~ Deviant*Session + (1|Subject),data=MMN2[MMN2$Time > 200 & MMN2$Time < 205,],series.var=~Time,nperm=2,type='anova')
```
```r
Error in `*tmp*`[[i]] : 下标出界 # 下标出界 is 'subscript out of bounds' in Chinese
此外: Warning messages: # 此外 means 'in addition'
1: In x[, ii] : 下标出界
2: In x[, ii] : 下标出界
3: In x[, ii] : 下标出界
```

Currently, I'm using treatment contrast to circumvent the problem but it's not suitable for running ANOVA type I assume. Really looking forward to your reply!

**Comment by cvoeten** [comment]
Thanks for finding and also debugging this issue! Your analysis seems spot on to me. I've reworked the problematic bit of code and pushed a possible fix to GH (and amended it just now because I realized I had gotten the logic wrong). Can you test if the current GH version also solves your real-world problem?

**Comment by hy-lu** [comment]
Thank you for your timely reply and fix. I tested the GH version using a small batch of my data and I do believe the problem has been worked out pretty well! Though I did encounter some errors when using the full data, I think those were just about my data itself.
I'll open new issues if I find other bugs. :)

**Comment by cvoeten** [comment]
OK, closing then. It'll be a while since a new release will make it onto CRAN, since I just submitted v2.1.1 and CRAN don't appreciate rapid releases, but when I do release v2.2, this fix will be included.
