### ISSUE TITLE
Is it possible to use permutes to fit multinomial logistic mixed-effects regression

### ISSUE THREAD

**Issue by CogPriming** [cvoeten/permutes#5]
Hello Voeten,
thank you for developing the permutes, my question is whether it is possible to adopt permutes to fit multinomial logistic mixed-effects regression? thank you.

**Comment by cvoeten** [comment]
Yes, this already is possible, using perm.glmer, clusterperm.glmer, perm.glmmTMB, or clusterperm.glmmTMB. Are these not sufficient for your use case?

**Comment by CogPriming** [comment]
In the code example of perm.glmer(), the dependent variable is continuous rather than categorical. Actually, the sample code is the same as the function of perm.lmer(). So, I'm not sure whether there are some problems?

**Comment by cvoeten** [comment]
Closing old. Note that for *multi*nomial logistic regression, you can use multiple *bi*nomial models on relevant subsets of the data (e.g. one model for 1 vs 2 and one model for 1 vs 3, etc). A truly binomial model is not available in permutes, although this should be possible to (painstakingly) implement by creating a `perm.gam` function that allows use of `mgcv`'s `multinom` family. However, this is not currently on my agenda.
